services:
  mysql:
    image: mysql:8.0
    container_name: employee_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root2025
      MYSQL_DATABASE: employee_management
    volumes:
      - mysql_data:/var/lib/mysql

  flask:
    build: .
    container_name: employee_flask
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  mysql_data:
